#!/bin/bash

# Convierte a ePub
pandoc -S --toc --epub-metadata=../metadata.xml --epub-stylesheet=../js.css \
    -o aprendejs.epub aprendeJS.txt \
    prologo.md  1-intro.md 1-oo.md 2-js-navegador.md \
    3-node.md 4-rest-ajax.md




